[[redirects]]
  from = "https://www.tundra.nz"
  to = "https://www.glacier.nz"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://tundra.nz"
  to = "https://www.glacier.nz"
  status = 200
  force = true
  headers = {X-From = "Netlify"}